### PR TITLE
Add compatibility with newer versions of OpenResty

### PR DESCRIPTION
**Pull request by ton31337**
Add compatibility with newer versions of OpenResty.

screen shot 2016-01-29 at 07 38 42

### CODE REVIEW

**Comment by priestjim** [comment]
Please don't increase the cookbook's version number in pull requests!

**Comment by ton31337** [comment]
fixed

**Comment by ton31337** [comment]
@priestjim any plans when if would be uploaded to chef supermarket with new version?

**Comment by priestjim** [comment]
Today :)

**Pull request merged**
