### PR TITLE
Logrotate attributes

### PR DESCRIPTION
**Pull request by klamontagne**
I need some flexibility in my logrotate options (`dateext` and 30 days). This turn the defaults into attributes.

### CODE REVIEW

**Comment by scalp42** [comment]
@klamontagne any chance you could make it a hash instead? Key being the directive and value `on/off`.

**Comment by priestjim** [comment]
I think the way it's structured is correct. If you don't want an option, simply don't define it in the array.

**Comment by scalp42** [comment]
@priestjim this won't work correctly FYI in Chef.

**Comment by klamontagne** [comment]
I know about the loss of ordering but this should not be a concern here.

**Comment by klamontagne** [comment]
I'm okay with redoing it with hashes if it's preferable. It doesn't matter much at this point.

**Comment by priestjim** [comment]
@klamontagne +1

**Comment by scalp42** [comment]
This is not related to a loss of ordering. If you have a wrapper cookbook and you try to override the array, it'll get merged with the ones by default.

So you can't override specifying an empty array on the `default` level.

**Comment by priestjim** [comment]
This is not the case in any of the Chef (12.6.0) deployments I have. I always override with

    attribute  = node['attribute'] | [:new_attribte]

in the wrapper cookbook. Simply specifying the attribute such as

    attribute = [:this, :new, :array]

will overwrite the previous array. Merging, as I see it, only occurs on role file overrides.

**Pull request merged**
